apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: python
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
      	app: python
    spec:
      imagePullSecrets:
      - name: ofekproj
      containers:
        - name: {{ .Release.Name }}
          image: 517056076755.dkr.ecr.us-east-1.amazonaws.com/ofekproj:latest
          imagePullPolicy: Always
          resources:
          limits:
            cpu: 0.8
            memory: 300Mi
          requests:
            cpu: 0.5
            memory: 200Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
         
